### Basic data type, string, and process control

In [2]:
println("Hello world")
println("Hello")

Hello world
Hello


In [11]:
a = 1 + 1
typeof(a)

Int64

In [12]:
a = "Hello"
typeof(a)

String

In [18]:
#For loop
x = 0
for k in 1:10000
    x = x + (π/k)^2
end
print(x)

16.233861594573302

In [20]:
#Nested For loop
for i in 1:3
    for j in 1:2
        print("i=", i, " j=", j, "\n")
    end
end

i=1 j=1
i=1 j=2
i=2 j=1
i=2 j=2
i=3 j=1
i=3 j=2


In [22]:
#Comprehensive for loop
for i ∈ 1:3, j ∈ 1:2
    print("i= ",i, " j=",j,"\n")
end

i= 1 j=1
i= 1 j=2
i= 2 j=1
i= 2 j=2
i= 3 j=1
i= 3 j=2


In [27]:
# bool is a subtype of interger
#so
true + true == 2

true

In [31]:
#concatenate strings
print(string("Hello"," ","Words","\n"))
print(string(1/7))

Hello Words
0.14285714285714285

In [36]:
#Format strings
print("$(1/7)")
print("\n")

0.14285714285714285


In [40]:
using Printf
@sprintf("%6.4f",1/7)  # Returns `"0.1429"`

"0.1429"

In [41]:
rmse = 1.5; mse = 1.1; R2 = 0.94
"Our model has a R^2 of $(R2), rmse of $(rmse), and mse of $(mse)"

"Our model has a R^2 of 0.94, rmse of 1.5, and mse of 1.1"

In [51]:
#Break and continue statement
x = 0
for k in 1:10000
    term = (1/k)^2
    x = x + term
    if (abs(term) < 1e-10) break end
end
x

1.6448340718480652

In [55]:
#continue:
# A reasonable use-case for the continue statement is as some sort of precondition-test for a bad argument passed to a loop.
numbers = randn(100)
sum = 0
for k in numbers
    if (k ==0) continue end
    sum += (1/k)
end
sum

38.92762402156585

In [61]:
numbers = randn(100)
sum = 0
for k in numbers
    if (k != 0)
        sum = sum + 1/k
    end
end
using Printf
print(@sprintf("Sum is %.3f", sum))
# more naturally if written this way

Sum is 316.730

### Function

In [62]:
function sum_zeta(s, nterms)
    x = 0
    for n in 1:nterms
        x = x + (1/n)^s
    end
    return x
end

sum_zeta (generic function with 1 method)

In [63]:
sum_zeta(2,10000)

1.6448340718480652

In [78]:
function circle(r)
    area = π * r^2
    cicum = 2π * r
    return area, cicum
end

a,c = circle(2)
(a,c)

(12.566370614359172, 12.566370614359172)

In [3]:
#! means the parameters pass in the func will be modified
function add_one!(x)
    x .= x .+ 1
end

x = [1,2,3]
add_one!(x);    # x is now [2,3,4]
x

3-element Vector{Int64}:
 2
 3
 4

In [85]:
#=
multiple
lines
annotation
=#

### Arrays

In [1]:
#Arrays
A = [
    1 2 3;
    1 2 4;
    2 2 2
]
A

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 2  2  2

In [2]:
# The same as above; more concise
A = [1 2 3; 1 2 4; 2 2 2]
A

3×3 Matrix{Int64}:
 1  2  3
 1  2  4
 2  2  2

In [3]:
b1 = [4.0, 5, 6]                # 3-element Vector{Float64}
b2 = [4.0; 5; 6]                # 3-element Vector{Float64}
m1 = [4.0 5 6]                  # 1×3 Matrix{Float64}

1×3 Matrix{Float64}:
 4.0  5.0  6.0

In [5]:
A = ["Hello", 1, 2, 3]
A

# whitespace -> Matrix
#comma or semicolon -> Vector

4-element Vector{Any}:
  "Hello"
 1
 2
 3

In [7]:
# array comprehension
v = [1/n^2 for n = 1:10000]
x = sum(v)

1.644834071848061

In [8]:
# generator
gen = (1/n^2 for n=1:10000)
x = sum(gen)

1.6448340718480652

In [9]:
#undefined arrays
#The reason to declare undefined arrays is to be able to fill them later — for example, with the use of a for loop.

n = 5
A1 = Array{Float64}(undef,n,n)          # 5×5 Matrix{Float64}
A2 = Matrix{Float64}(undef,n,n)         # 5×5 Matrix{Float64}

V1 = Array{Float64}(undef,n)            # 5-element Vector{Float64}
V2 = Vector{Float64}(undef,n)           # 5-element Vector{Float64}

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [10]:
# To specify type
v = Float64[]

Float64[]

In [11]:
#special kind of arrays
A = zeros(8,8)
B = ones(3,3)


3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [13]:
C = rand(3,3,1)

3×3×1 Array{Float64, 3}:
[:, :, 1] =
 0.306494   0.115779  0.644294
 0.673215   0.393963  0.592625
 0.0913278  0.76805   0.51975

In [15]:
using LinearAlgebra
M = 5I + rand(2,2)

2×2 Matrix{Float64}:
 5.04168    0.808613
 0.0766023  5.16764

### Array function and dot operartor

easily turn a function than accepts a scalar value, 
    and apply it element-wise to an array. 
The way to do this is to employ a ‘dot’ 
after the function’s name.


In [18]:
# define a func
f(x) = 3x^3/(1+x^2)
x = [2π / n for n = 1:3]
y = f.(x)

3-element Vector{Float64}:
 18.383886633134814
  8.55770151410267
  5.11671431742654

In [19]:
y = sin.(x)

3-element Vector{Float64}:
 -2.4492935982947064e-16
  1.2246467991473532e-16
  0.8660254037844387

### Indexing and Slicing

In [22]:
A = rand(6)
print(A)
A[begin]
    
A[end]

[0.5705246965265665, 0.526303100526652, 0.7750808332292207, 0.9904576110903489, 0.4771486453597087, 0.3685079828615606]

0.3685079828615606

In [29]:
#slicing
A = rand(6,6)

# extract the odd indices 
#in both dimensions from a 6x6 matrix
B = A[begin:2:end,begin:2:end]

3×3 Matrix{Float64}:
 0.134753   0.984971  0.875538
 0.0619011  0.71055   0.96637
 0.167132   0.531287  0.832167

In [35]:
#Logical Indexing
A = rand(6,6)
#@. element wise
@. A[ A < 0.5] =0
A

6×6 Matrix{Float64}:
 0.0       0.0       0.588084  0.0       0.0       0.0
 0.0       0.0       0.858886  0.537348  0.0       0.0
 0.0       0.0       0.878515  0.0       0.0       0.0
 0.783599  0.878829  0.0       0.66177   0.0       0.634533
 0.513767  0.901853  0.0       0.0       0.956552  0.631326
 0.939417  0.539452  0.0       0.0       0.830601  0.0

In [37]:
A = rand(6)
for i ∈ eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.41014609052794815
i=2 A[i]=0.3531342600681986
i=3 A[i]=0.8665995289509187
i=4 A[i]=0.08654276909839909
i=5 A[i]=0.18008023947306684
i=6 A[i]=0.13791802222299665


In [41]:
A = rand(6)
for i in eachindex(A)
    println(string("i=$(i) A[i]=$(A[i])"))
end

i=1 A[i]=0.06186664850574786
i=2 A[i]=0.3248207525966803
i=3 A[i]=0.6654737931034029
i=4 A[i]=0.6606263863003327
i=5 A[i]=0.08601371887954745
i=6 A[i]=0.7573126174544177


In [44]:
A = rand(2,3)
for i ∈ 1:size(A,1), j ∈ 1:size(A,2)
    println(string("i=$(i) j=$(j) A[i,j]=$(A[i,j])"))
end

i=1 j=1 A[i,j]=0.6793025350584356
i=1 j=2 A[i,j]=0.8422731304786125
i=1 j=3 A[i,j]=0.6755511910178371
i=2 j=1 A[i,j]=0.594250748072436
i=2 j=2 A[i,j]=0.06985634866624402
i=2 j=3 A[i,j]=0.007857501745935469


### Resize and Concat Arrays

In [45]:
A = Float64[]       # Equivalent to A=Array{Float64}(undef,0)
push!(A, 4)         # Adds the number 4 at the end of the array
push!(A, 3)         # Adds the number 3 at the end of the array
v = pop!(A)         # Returns 3 and removes it from A

3.0

In [46]:
A = [4 5 6] 
B = [6 7 8] 

M1 = vcat(A, B)

M2 = hcat(A, B)

println(M1)
println(M2)

[4 5 6; 6 7 8]
[4 5 6 6 7 8]


In [48]:
M1 = cat(A, B, dims=1)

2×3 Matrix{Int64}:
 4  5  6
 6  7  8

In [49]:
M2= cat(A, B, dims=2)

1×6 Matrix{Int64}:
 4  5  6  6  7  8